use_frameworks!

platform :ios, '13.0'

target 'ZHHInteractivePush_Example' do
  pod 'ZHHInteractivePush', :path => '../'

  target 'ZHHInteractivePush_Tests' do
    inherit! :search_paths

    
  end
end
